[tool.poetry]
name = "rai-bot"
version = "0.1.0"
description = "ChatGPT clone with FastAPI and PostgreSQL"
authors = ["Vladyslav Timofieiev <vladislav.tmf@gmail.com>"]
readme = "README.md"
packages = [{include = "backend"}]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {extras = ["all"], version = "^0.115.11"}
sqlalchemy = "^2.0.39"
alembic = "^1.15.1"
python-jose = {extras = ["cryptography"], version = "^3.4.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
beautifulsoup4 = "^4.13.3"
asyncpg = "^0.30.0"
openai = "^1.66.2"
bcrypt = "4.0.1"


[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
flake8 = "^7.1.2"
flake8-pyproject = "^1.2.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ["py312"]
extend-exclude = "backend/alembic/versions"

[tool.flake8]
max-line-length = 88
extend-exclude = ["backend/alembic/versions"]
